param(
    [string]$Tag = "v0.x.y-short-name"
)

Write-Host "# $Tag"
Write-Host ""
Write-Host "## Summary"
Write-Host ""
Write-Host "## Added"
Write-Host "- "
Write-Host ""
Write-Host "## Changed"
Write-Host "- "
Write-Host ""
Write-Host "## Fixed"
Write-Host "- "
Write-Host ""
Write-Host "## Verification"
Write-Host '- `.\scripts\check-release-claims.ps1`'
Write-Host '- `.\scripts\local-release-verify.ps1`'
Write-Host ""
Write-Host "## Known Limits"
Write-Host "- No embedded I2P router"
Write-Host "- No WebView/full browser"
Write-Host "- No JavaScript execution"
Write-Host "- No VPN"
Write-Host "- No Tor"
Write-Host "- No secure chat"
Write-Host "- Debug APK only unless otherwise stated"
Write-Host ""
Write-Host "## Non-goals"
Write-Host "- Production signing"
Write-Host "- Play Store publishing"
Write-Host "- Anonymous browsing guarantees"
