$ErrorActionPreference = "Stop"

Write-Host "Expected GitHub Actions artifact:"
Write-Host "  i2p-knoks-debug-apk"
Write-Host ""
Write-Host "Expected APK path:"
Write-Host "  app/build/outputs/apk/debug/*.apk"
Write-Host ""
Write-Host "Expected checksum artifact:"
Write-Host "  i2p-knoks-debug-apk-sha256"
Write-Host ""
Write-Host "Expected checksum file:"
Write-Host "  app-debug.apk.sha256"
Write-Host ""
Write-Host "Build type:"
Write-Host "  debug"
Write-Host ""
Write-Host "Intended use:"
Write-Host "  real-alpha testing only"
Write-Host ""
Write-Host "Checksum verification (Linux/macOS):"
Write-Host "  sha256sum -c app-debug.apk.sha256"
Write-Host ""
Write-Host "Checksum verification (Windows PowerShell):"
Write-Host "  (Get-FileHash app-debug.apk -Algorithm SHA256).Hash"
Write-Host ""
Write-Host "Not production signed. Not a Play Store release."
