$ErrorActionPreference = "Stop"

Write-Host "Expected GitHub Actions artifact:"
Write-Host "  i2p-knoks-debug-apk"
Write-Host ""
Write-Host "Expected APK path:"
Write-Host "  app/build/outputs/apk/debug/*.apk"
Write-Host ""
Write-Host "Build type:"
Write-Host "  debug"
Write-Host ""
Write-Host "Intended use:"
Write-Host "  real-alpha testing only"
Write-Host ""
Write-Host "Not production signed. Not a Play Store release."
